# Generated by Django 3.0.8 on 2020-07-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
