# Generated by Django 3.0.8 on 2020-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200727_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='is_activated',
            field=models.CharField(default='Y', max_length=10),
        ),
    ]
