# Generated by Django 3.0.8 on 2020-07-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200727_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='sub_description',
        ),
    ]
