# Generated by Django 3.0.8 on 2020-07-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200727_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_description',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_activated',
            field=models.CharField(blank=True, default='Y', max_length=10),
        ),
    ]
