# Generated by Django 3.0.8 on 2020-07-27 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200727_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_description',
            new_name='title_description',
        ),
    ]
