# Generated by Django 3.0.8 on 2020-07-27 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200727_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='sub_description',
            new_name='description_content',
        ),
    ]
