# Generated by Django 3.0.8 on 2020-07-27 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200727_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description_cont',
            new_name='description_title',
        ),
    ]
