# Generated by Django 3.0.8 on 2020-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200730_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='is_activated',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_activated',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
