# Generated by Django 3.0.7 on 2020-07-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characteristic',
            old_name='smell',
            new_name='scent',
        ),
    ]
