# Generated by Django 3.0.8 on 2020-07-30 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_recommendation_recommendationitems'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facetypeproduct',
            old_name='faceType',
            new_name='face_type',
        ),
    ]
