# Generated by Django 3.0.8 on 2020-07-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20200730_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='facetype',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='facetypeproduct',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='howtouse',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='pricebysize',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recommendationitems',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='usability',
            name='is_activated',
            field=models.CharField(blank=True, default=True, max_length=10),
        ),
    ]
