# Generated by Django 3.0.7 on 2020-07-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200725_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='subscrition',
            new_name='subscription',
        ),
    ]
